[package]
name = "advent2023"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "1"
path = "src/1/main.rs"

[[bin]]
name = "2"
path = "src/2/main.rs"

[[bin]]
name = "3-1"
path = "src/3/part1/main.rs"

[[bin]]
name = "3-2"
path = "src/3/part2/main.rs"

[dependencies]
